### ISSUE TITLE
Innkeeper Camp Taurajo - strange quest in dialogue option

### ISSUE THREAD

**Issue by Halahlstrom** [darrowshire-dev/bugtracker#10]
https://classic.wowhead.com/npc=7714/innkeeper-byula - Innkeeper in Camp taurajo

Screenshot illustrates strange quest option when selecting the dialogue option "Tell me about dungeons I could explore."

![image](https://user-images.githubusercontent.com/64362843/113657835-128b0800-969f-11eb-9693-fee65114927c.png)

**Comment by darrowshire-dev** [comment]
--fixed
