### ISSUE TITLE
party members not getting roll window when loot drops and they are far away inside an instance

### ISSUE THREAD

**Issue by ronaldofenomeno** [darrowshire-dev/bugtracker#100]
![image](https://user-images.githubusercontent.com/33092150/122071737-0a221c80-ce08-11eb-9e82-dc91031b8afc.png)

if a player loots a corpse and it has a green item which you can roll for, other far way members who are in the instance wont get to roll for the item. i tried with one party member and killed a boss while he was far away. when i looted the corpse no roll window appeard. i won the item stright away.
![image](https://user-images.githubusercontent.com/33092150/122072308-81f04700-ce08-11eb-81f2-cc67e7775ef6.png)

i remember on classic that all players of the party inside the instance get the roll window for any loot green or higher whether they are near the boss/mob or far away.

**Comment by MoneyControlStockScraper** [comment]
So when i kill the boss and party member is far away, the green loot instantly comes to my backpack saying "You won: [Green item]
![AnyConv com__WoWScrnShot_061521_201904 (1)](https://user-images.githubusercontent.com/84612798/122075017-5aed4180-ce17-11eb-8b87-6276baf73095.jpg)

**Comment by Pirupuku** [comment]
I think that's normal behaviour in world/dungeon environment, however in a raid e.g. MC if the raid kills Sulfuron and you are inside at the entrance of the raid, you should be able to roll for the item or at least be able to get it via Master Loot.

**Comment by ronaldofenomeno** [comment]
> This is normal. If your partymember is too far away (like really really far) you dont get a loot roll.
> But here comes the strange thing. In instances the the lootwindows should appear. Thank you for reporting this!

i remember on classic that inside the instances, any item drop will get a you roll window no matter where you are in the instance whether far away from the corpse or not

but in the outside world if you are far away you wont get any roll window

**Comment by ronaldofenomeno** [comment]
on the change log in discord it says that it is fixed. but it still isnt
![image](https://user-images.githubusercontent.com/33092150/123342061-bcb85480-d557-11eb-9252-15048400d6ae.png)
