### ISSUE TITLE
Wailing Caverns Mutanus the Devourer did not cast Fear

### ISSUE THREAD

**Issue by MoneyControlStockScraper** [darrowshire-dev/bugtracker#103]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged?
https://classic.wowhead.com/npc=3654/mutanus-the-devourer#abilities;mode:normal

--Current Behaviour: Does not cast Terrify
--Expected Behaviour:
He should instant cast Terrify/fear, please take a look at the video, we gave him time to cast by killing slowly.

https://user-images.githubusercontent.com/84612798/122078019-e23bb480-ce19-11eb-87b2-34013ac06a2a.mp4

**Comment by darrowshire-dev** [comment]
will be adressed.
