### ISSUE TITLE
Instance mobs not linked (aggro)

### ISSUE THREAD

**Issue by MoneyControlStockScraper** [darrowshire-dev/bugtracker#104]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged?
https://classic.wowhead.com/npc=3840/druid-of-the-fang
https://classic.wowhead.com/npc=5048/deviate-adder

--Current Behaviour:
The mob is located immediately after the boss skum. The room was cleared but this mob did not aggro
![AnyConv com__WoWScrnShot_061521_201514](https://user-images.githubusercontent.com/84612798/122152597-2a40f280-ce7f-11eb-90eb-8a4ff801187a.jpg)

Another mob deviate adder shows the same behaviour. I dont have screenshot but it is present near the second boss (lord cobran)

--Expected Behaviour: Both these mobs should aggro when mobs around them are killed.

**Comment by darrowshire-dev** [comment]
-- will be adressed. Thank you for your report! :)

**Comment by MoneyControlStockScraper** [comment]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged?
https://classic.wowhead.com/npc=4805/blackfathom-sea-witch
https://classic.wowhead.com/npc=4799/fallenroot-hellcaller
https://classic.wowhead.com/npc=4815/murkshallow-snapclaw
https://classic.wowhead.com/npc=4813/twilight-shadowmage

--Current Behaviour: Does not aggro
![2](https://user-images.githubusercontent.com/84612798/122663031-3990aa80-d1b5-11eb-8598-2a0150486c6a.jpeg)
![3](https://user-images.githubusercontent.com/84612798/122663033-3ac1d780-d1b5-11eb-936b-8919683481cf.jpeg)
![4](https://user-images.githubusercontent.com/84612798/122663035-3b5a6e00-d1b5-11eb-986a-937df2cca4cf.jpeg)
![1](https://user-images.githubusercontent.com/84612798/122663037-3bf30480-d1b5-11eb-9beb-5f13675d9832.jpeg)


PS: Most of the mobs are linked propperly, just a few of them are not.

**Comment by MoneyControlStockScraper** [comment]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged?
https://classic.wowhead.com/npc=3927/wolf-master-nandos

--Current Behaviour: When you kill the first worg on the left, all 4 worgs come and attack you but the wolf master does not aggro.
![1](https://user-images.githubusercontent.com/84612798/122663059-66dd5880-d1b5-11eb-9762-76eb3a3d7720.jpg)


Later, when you kill the 4 wolves, he says his dialogue, runs across the room and stands in the corridor through which party enters the boss arena.
![2](https://user-images.githubusercontent.com/84612798/122663064-7066c080-d1b5-11eb-8e74-c3eeabdac21e.jpg)


--Expected Behaviour:
Boss should aggro along with his wolves.

**Comment by MoneyControlStockScraper** [comment]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged?
Mobs in SM https://classic.wowhead.com/npc=4540/scarlet-monk

--Current Behaviour: As seen in the video, the first 2 mobs are linked and one aggros if you attack the other. This is the correct behaviour.

But when you move one mob near another pack (away from the aggroed spawn point), they do not aggro untill the first mob becomes low hp and runs in fear. Some mobs do not run in fear and thus, the mob pack does not aggro you until you attack them.


https://user-images.githubusercontent.com/84612798/122663131-e66b2780-d1b5-11eb-8ff3-5967c33e14e7.mp4


This behaviour is seen across many instances.

--Expected Behaviour: Mob packs should aggro if you are in combat with another mob near them even if the spawn point of the mob in combat with you is far away.

PS: I took video of only one example, but many mobs are not linked in a similar manner.

Here are few more screenshots of mobs showing same behaviour.
![3](https://user-images.githubusercontent.com/84612798/122663140-f2ef8000-d1b5-11eb-930e-e1e807ad1cf4.png)
![1](https://user-images.githubusercontent.com/84612798/122663143-f420ad00-d1b5-11eb-9acf-9dd26865fa96.png)
![2](https://user-images.githubusercontent.com/84612798/122663144-f4b94380-d1b5-11eb-9a97-8184f257b549.png)
