### ISSUE TITLE
Unable to mount inside water but not swimming

### ISSUE THREAD

**Issue by ronaldofenomeno** [darrowshire-dev/bugtracker#108]
![image](https://user-images.githubusercontent.com/33092150/122472339-8582fa00-cfd1-11eb-962e-f534fc2fb80f.png)

i am unable to mount up while im in the water but not swimming. im still standing.

you should be able to mount up while standing even if you are in the water but if you are not swimming.

**Comment by darrowshire-dev** [comment]
Please try to use one of the other mounts. Like normal ones, not the legendary drake.

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/c3f4058133488edd146b96185ad61e95cf8e14c5

**Comment by ronaldofenomeno** [comment]
tried with another mount, also not working
![image](https://user-images.githubusercontent.com/33092150/123154117-23157800-d46f-11eb-8b61-b8e984c2cd25.png)
