### ISSUE TITLE
Got credit for kodo roundup quest 3 times from one kodo due to lag

### ISSUE THREAD

**Issue by ronaldofenomeno** [darrowshire-dev/bugtracker#113]
![image](https://user-images.githubusercontent.com/33092150/122680321-94e78a80-d1ff-11eb-9216-153794d3db7a.png)

I had lag and right clicked the kodo several times to turn in, when the lag went away i got credits until the quest completed just by right clicking the single kodo during the lag.

**Comment by Godmatik** [comment]
@darrowshire-dev 

It's not fixed. You can multiple click on the Kodo when you bring it in and get credit twice
