### ISSUE TITLE
Humanoids drop too much gold

### ISSUE THREAD

**Issue by xdfire** [darrowshire-dev/bugtracker#123]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged?
https://classic.wowhead.com/npc=3119/kolkar-drudge
https://classic.wowhead.com/npc=3120/kolkar-outrunner
https://classic.wowhead.com/npc=3101/vile-familiar

-- Current behaviour:
Kolkars drop up to 65c
Familiars drop up to 40c

-- Expected behaviour:
Money drops should be much lower, see data on wowhead
and https://www.youtube.com/watch?v=g-1A-JD2UMQ @9min 20s    @39min
I suspect this is a much larger issue than these 3 NPCs

**Comment by MoneyControlStockScraper** [comment]
![2021-06-26 18_38_43-Greenshot](https://user-images.githubusercontent.com/84612798/123513981-d8ce0a00-d6ad-11eb-84bc-1e3ca5487352.png)

**Comment by ronaldofenomeno** [comment]
i believe that the droprate on the ptr is increased
