### ISSUE TITLE
Vorsha the Lasher escort quest

### ISSUE THREAD

**Issue by ronaldofenomeno** [darrowshire-dev/bugtracker#128]
https://classic.wowhead.com/quest=6641/vorsha-the-lasher
Nothing happens when i right click on the blazier to put it out. no waves of enemies come at all
![image](https://user-images.githubusercontent.com/33092150/124308454-fb5e9800-db71-11eb-9419-4f20f5e05f6b.png)

**Comment by ratkosrb** [comment]
This should resolve issues with the brazier https://github.com/vmangos/core/commit/1b82e62581e596e134c35e3f361554e2d9e7192d
