### ISSUE TITLE
2h weapon skill bug

### ISSUE THREAD

**Issue by MoneyControlStockScraper** [darrowshire-dev/bugtracker#129]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
Weapon skills

-- Current behaviour: Can use 2h Axe without talent as shamann.
![2021-07-06 13_12_16-Greenshot](https://user-images.githubusercontent.com/84612798/124561857-fb091a00-de5b-11eb-82f6-88e28a29894f.png)

-- Current behaviour: Should not be able to use 2h Axe without talent as shamann.

**Comment by ratkosrb** [comment]
What did you do to cause it?

**Comment by MoneyControlStockScraper** [comment]
> What did you do to cause it?

I think this bug is exclusive to this ptr, not a vmangos bug
