### ISSUE TITLE
mail bug

### ISSUE THREAD

**Issue by MoneyControlStockScraper** [darrowshire-dev/bugtracker#130]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
mailbox

-- Current behaviour:  I have cleared the cache/wdb folder and yet, The mail icon is shown on the minimap but no mail to be seen at the mailbox.
![2021-07-06 15_11_43-Greenshot](https://user-images.githubusercontent.com/84612798/124579378-ade17400-de6c-11eb-86f6-61304ad03a45.png)

-- Expected behaviour: If the mail icon is shown on the minimap, mail should be shown in the mailbox as well.

**Comment by ratkosrb** [comment]
Somebody must have sent you something but it has not arrived yet.

**Comment by MoneyControlStockScraper** [comment]
> Somebody must have sent you something but it has not arrived yet.

Been like this for 3 days
