### ISSUE TITLE
Stealth detection bug

### ISSUE THREAD

**Issue by MoneyControlStockScraper** [darrowshire-dev/bugtracker#131]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
enemy stealth detection range

-- Current behaviour: Range is way too short. Only aggro when u stand on top of them.

https://user-images.githubusercontent.com/84612798/124605009-1e968980-de89-11eb-9216-7154ac3c1c75.mp4

-- Expected Behaviour: They should aggro like the high level mob even if they are lower level.

**Comment by ratkosrb** [comment]
The stealth detection range in vmangos has been measured against official Classic servers and produces identical results.

- There is a minimum detection distance of 1.5 yards.
- For creatures detecting players, the base value is 0.8 and it increases by 0.8 for every level the mob is higher than you.

So versus same level mob, it will detect you 1.5 yards away. If its 1 level higher than you, it will detect you at 1.6 yards. If its 2 levels higher, it will detect you at 2.4 yards away. If its 3 levels higher, it will detect you 3.2 yards away. Et cetera.

So I would classify this issue as not a bug. It is correct that the same level mob only detects you once you basically touch it.

**Comment by MoneyControlStockScraper** [comment]
Thank you for your interest and help with these bugs!

Hope you have a great day!
