### ISSUE TITLE
Mobs walking over objects (unfixed)

### ISSUE THREAD

**Issue by ronaldofenomeno** [darrowshire-dev/bugtracker#132]
https://github.com/darrowshire-dev/bugtracker/issues/28

it says that the issues were fixed. if the fixes are applied on the ptr then none of these issues were actually fixed. i just checked them. they are still there.

**Comment by ratkosrb** [comment]
To fix this you'd need to reduce the max walkable angle when generating mmaps, but then every object would serve as a reset spot and mobs would evade if you stood on it. And I am not even sure if its actually a bug from an emulation point of view (if its possible for this to happen on official servers).
