### ISSUE TITLE
War Golem Rare Spawn (located in Badlands)

### ISSUE THREAD

**Issue by BugTestR** [darrowshire-dev/bugtracker#137]
<strike>When attacking War Golem Rare mob, it casts a spell called Lock Down. The issue is that when it casts that said spell, it is then casted on itself and not on the player or mob that is attacking it with the highest threat.  This is a copy paste from wowhead of the spell:  https://classic.wowhead.com/npc=2751/war-golem#abilities</strike>

**Comment by ratkosrb** [comment]
The spell description says:
```
Immobilizes the caster and increases the Physical damage it deals by 50 for 10 sec.
```

So that means it should get casted on the mob.

**Comment by BugTestR** [comment]
You're right sorry, disregard this.
