### ISSUE TITLE
Mob Not using abilities thread.

### ISSUE THREAD

**Issue by MoneyControlStockScraper** [darrowshire-dev/bugtracker#139]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
Darkshore:
https://classic.wowhead.com/npc=2189/vile-sprite#abilities - Does not cast posion
https://classic.wowhead.com/npc=2181/stormscale-myrmidon#abilities  - Does not cast knockdown
https://classic.wowhead.com/npc=2236/raging-reef-crawler#abilities -  - Does not cast thrash
https://classic.wowhead.com/npc=10158/moonkin#abilities -  - Does not cast thrash
https://classic.wowhead.com/npc=2156/cracked-golem#abilities  - Does not cast stone skin
https://classic.wowhead.com/npc=2206/greymist-hunter -  - Does not cast throw

Ashenvale:
https://classic.wowhead.com/npc=3750/foulweald-totemic#abilities  - Does not cast corrupted intellect
https://classic.wowhead.com/npc=3743/foulweald-warrior#abilities  - Does not cast corrupted strength
https://classic.wowhead.com/npc=3806/forsaken-infiltrator#abilities -  - Does not cast poison
https://classic.wowhead.com/npc=3771/bleakheart-hellcaller#abilities -  - Does not cast curse 
https://classic.wowhead.com/npc=3767/bleakheart-trickster - Does not cast curse
https://classic.wowhead.com/npc=3770/bleakheart-shadowstalker#abilities - Does not cast curse
https://classic.wowhead.com/npc=3765/bleakheart-satyr - Does not cast curse

-- Current behaviour:  does not use its abilities.

- Expected behaviour:  ​Should use its abilities.

**Comment by rosen40** [comment]
Most of these creature already have scripts for all of these spells on vmangos, but the scripting on vmangos is pretty bad, most of the scripts are broken. I'll go into more detail below and also provide fixes. I have a whole lotta more fixes where those came from, so @Radiixx, test the fixes i provide here and you'll see that i am not bullshitting. After that you can contact me on disc, Tyraxor#9192 if you want to get the rest of them.


https://classic.wowhead.com/npc=2189/vile-sprite#abilities - Does not cast posion    <---- has so many different spells called poison listed, which one should it be?

https://classic.wowhead.com/npc=2236/raging-reef-crawler#abilities - - Does not cast thrash
https://classic.wowhead.com/npc=10158/moonkin#abilities - - Does not cast thrash
^ these guys do thrash, its just not shown in combat log because its just extra normal attacks. Nevertheless, they use thrash on a timer on the PTR so the ability is at least not missing, but its wrong to be on a timer, it should be a passive aura with proc chance.

The rest of the abilties are really missing due to their scripts being broken.

**Comment by rosen40** [comment]
/* Stormscale Myrmidon */

update creature_template set auras = 6961 where entry = 2181;

DELETE FROM `creature_ai_scripts` WHERE `id` IN (218101);

DELETE FROM `creature_ai_events` WHERE `creature_id`=2181;

INSERT INTO `creature_ai_events` (`id`, `creature_id`, `condition_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_script`, `action2_script`, `action3_script`, `comment`) VALUES (218101, 2181, 0, 2, 0, 100, 0, 15, 0, 0, 0, 6000000, 0, 0, 'Stormscale Myrmidon - Flee at 15\%');

/* Raging Reef Crawler */

delete from creature_spells where entry = 22360;
update creature_template set auras = 3417, spell_list_id = 0, ai_name = '' where entry = 2236;

/* Moonkin */

delete from creature_spells where entry = 101580;
update creature_template set auras = 3417, spell_list_id = 0, ai_name = '' where entry = 10158;

/* Greymist Hunter */

update creature_template set spell_list_id = 22060, ai_name = 'EventAI' where entry = 2206;

DELETE FROM `creature_ai_events` WHERE `creature_id`=2206;

INSERT INTO `creature_ai_events` (`id`, `creature_id`, `condition_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_script`, `action2_script`, `action3_script`, `comment`) VALUES (220601, 2206, 0, 33, 0, 100, 1, 15000, 15000, 0, 0, 6000002, 0, 0, 'Greymist Hunter - Run Away on Rooted Target Manaless');

INSERT INTO `creature_ai_events` (`id`, `creature_id`, `condition_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_script`, `action2_script`, `action3_script`, `comment`) VALUES (220602, 2206, 0, 2, 0, 100, 0, 15, 0, 0, 0, 6000000, 0, 0, 'Greymist Hunter - Flee at 15\%');

REPLACE INTO `creature_spells` (`entry`, `name`, `spellId_1`, `probability_1`, `castTarget_1`, `targetParam1_1`, `targetParam2_1`, `castFlags_1`, `delayInitialMin_1`, `delayInitialMax_1`, `delayRepeatMin_1`, `delayRepeatMax_1`, `scriptId_1`, `spellId_2`, `probability_2`, `castTarget_2`, `targetParam1_2`, `targetParam2_2`, `castFlags_2`, `delayInitialMin_2`, `delayInitialMax_2`, `delayRepeatMin_2`, `delayRepeatMax_2`, `scriptId_2`, `spellId_3`, `probability_3`, `castTarget_3`, `targetParam1_3`, `targetParam2_3`, `castFlags_3`, `delayInitialMin_3`, `delayInitialMax_3`, `delayRepeatMin_3`, `delayRepeatMax_3`, `scriptId_3`, `spellId_4`, `probability_4`, `castTarget_4`, `targetParam1_4`, `targetParam2_4`, `castFlags_4`, `delayInitialMin_4`, `delayInitialMax_4`, `delayRepeatMin_4`, `delayRepeatMax_4`, `scriptId_4`, `spellId_5`, `probability_5`, `castTarget_5`, `targetParam1_5`, `targetParam2_5`, `castFlags_5`, `delayInitialMin_5`, `delayInitialMax_5`, `delayRepeatMin_5`, `delayRepeatMax_5`, `scriptId_5`, `spellId_6`, `probability_6`, `castTarget_6`, `targetParam1_6`, `targetParam2_6`, `castFlags_6`, `delayInitialMin_6`, `delayInitialMax_6`, `delayRepeatMin_6`, `delayRepeatMax_6`, `scriptId_6`, `spellId_7`, `probability_7`, `castTarget_7`, `targetParam1_7`, `targetParam2_7`, `castFlags_7`, `delayInitialMin_7`, `delayInitialMax_7`, `delayRepeatMin_7`, `delayRepeatMax_7`, `scriptId_7`, `spellId_8`, `probability_8`, `castTarget_8`, `targetParam1_8`, `targetParam2_8`, `castFlags_8`, `delayInitialMin_8`, `delayInitialMax_8`, `delayRepeatMin_8`, `delayRepeatMax_8`, `scriptId_8`) VALUES (22060, 'Greymist Hunter', 10277, 100, 1, 0, 0, 8, 0, 0, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

**Comment by rosen40** [comment]
/* Foulweald Totemic */

update creature_template set auras = 6823 where entry = 3750;

DELETE FROM `creature_ai_scripts` WHERE `id` IN (375001, 375003);

DELETE FROM `creature_ai_events` WHERE `creature_id`=3750;

INSERT INTO `creature_ai_events` (`id`, `creature_id`, `condition_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_script`, `action2_script`, `action3_script`, `comment`) VALUES (375001, 3750, 0, 2, 0, 100, 0, 15, 0, 0, 0, 6000000, 0, 0, 'Foulweald Totemic - Flee at 15\%');

REPLACE INTO `creature_spells` (`entry`, `name`, `spellId_1`, `probability_1`, `castTarget_1`, `targetParam1_1`, `targetParam2_1`, `castFlags_1`, `delayInitialMin_1`, `delayInitialMax_1`, `delayRepeatMin_1`, `delayRepeatMax_1`, `scriptId_1`, `spellId_2`, `probability_2`, `castTarget_2`, `targetParam1_2`, `targetParam2_2`, `castFlags_2`, `delayInitialMin_2`, `delayInitialMax_2`, `delayRepeatMin_2`, `delayRepeatMax_2`, `scriptId_2`, `spellId_3`, `probability_3`, `castTarget_3`, `targetParam1_3`, `targetParam2_3`, `castFlags_3`, `delayInitialMin_3`, `delayInitialMax_3`, `delayRepeatMin_3`, `delayRepeatMax_3`, `scriptId_3`, `spellId_4`, `probability_4`, `castTarget_4`, `targetParam1_4`, `targetParam2_4`, `castFlags_4`, `delayInitialMin_4`, `delayInitialMax_4`, `delayRepeatMin_4`, `delayRepeatMax_4`, `scriptId_4`, `spellId_5`, `probability_5`, `castTarget_5`, `targetParam1_5`, `targetParam2_5`, `castFlags_5`, `delayInitialMin_5`, `delayInitialMax_5`, `delayRepeatMin_5`, `delayRepeatMax_5`, `scriptId_5`, `spellId_6`, `probability_6`, `castTarget_6`, `targetParam1_6`, `targetParam2_6`, `castFlags_6`, `delayInitialMin_6`, `delayInitialMax_6`, `delayRepeatMin_6`, `delayRepeatMax_6`, `scriptId_6`, `spellId_7`, `probability_7`, `castTarget_7`, `targetParam1_7`, `targetParam2_7`, `castFlags_7`, `delayInitialMin_7`, `delayInitialMax_7`, `delayRepeatMin_7`, `delayRepeatMax_7`, `scriptId_7`, `spellId_8`, `probability_8`, `castTarget_8`, `targetParam1_8`, `targetParam2_8`, `castFlags_8`, `delayInitialMin_8`, `delayInitialMax_8`, `delayRepeatMin_8`, `delayRepeatMax_8`, `scriptId_8`) VALUES (37500, 'Ashenvale - Foulweald Totemic', 6363, 100, 0, 0, 0, 0, 6, 9, 25, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

/* Foulweald Warrior */

update creature_template set auras = 6821 where entry = 3743;

DELETE FROM `creature_ai_scripts` WHERE `id` IN (374301, 374302);

DELETE FROM `creature_ai_events` WHERE `creature_id`=3743;

INSERT INTO `creature_ai_events` (`id`, `creature_id`, `condition_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_script`, `action2_script`, `action3_script`, `comment`) VALUES (374301, 3743, 0, 2, 0, 100, 0, 15, 0, 0, 0, 6000000, 0, 0, 'Foulweald Warrior - Flee at 15\%');

**Comment by ratkosrb** [comment]
Missing abilities have been added here https://github.com/vmangos/core/commit/d1530259ee74d4921b2f1919e4f4c314e67029c2

There was no issue with Raging Reef Crawler and Moonkin. They already cast Thrash.

**Comment by MoneyControlStockScraper** [comment]
Trisfal 

https://classic.wowhead.com/npc=1941/rot-hide-graverobber#abilities - not using curse
https://classic.wowhead.com/npc=1675/rot-hide-mongrel#abilities - not using curse
https://classic.wowhead.com/npc=1674/rot-hide-gnoll#abilities - not using curse

**Comment by MoneyControlStockScraper** [comment]
> /* Foulweald Totemic */
> 
> update creature_template set auras = 6823 where entry = 3750;
> 
> DELETE FROM `creature_ai_scripts` WHERE `id` IN (375001, 375003);
> 
> DELETE FROM `creature_ai_events` WHERE `creature_id`=3750;
> 
> INSERT INTO `creature_ai_events` (`id`, `creature_id`, `condition_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_script`, `action2_script`, `action3_script`, `comment`) VALUES (375001, 3750, 0, 2, 0, 100, 0, 15, 0, 0, 0, 6000000, 0, 0, 'Foulweald Totemic - Flee at 15%');
> 
> REPLACE INTO `creature_spells` (`entry`, `name`, `spellId_1`, `probability_1`, `castTarget_1`, `targetParam1_1`, `targetParam2_1`, `castFlags_1`, `delayInitialMin_1`, `delayInitialMax_1`, `delayRepeatMin_1`, `delayRepeatMax_1`, `scriptId_1`, `spellId_2`, `probability_2`, `castTarget_2`, `targetParam1_2`, `targetParam2_2`, `castFlags_2`, `delayInitialMin_2`, `delayInitialMax_2`, `delayRepeatMin_2`, `delayRepeatMax_2`, `scriptId_2`, `spellId_3`, `probability_3`, `castTarget_3`, `targetParam1_3`, `targetParam2_3`, `castFlags_3`, `delayInitialMin_3`, `delayInitialMax_3`, `delayRepeatMin_3`, `delayRepeatMax_3`, `scriptId_3`, `spellId_4`, `probability_4`, `castTarget_4`, `targetParam1_4`, `targetParam2_4`, `castFlags_4`, `delayInitialMin_4`, `delayInitialMax_4`, `delayRepeatMin_4`, `delayRepeatMax_4`, `scriptId_4`, `spellId_5`, `probability_5`, `castTarget_5`, `targetParam1_5`, `targetParam2_5`, `castFlags_5`, `delayInitialMin_5`, `delayInitialMax_5`, `delayRepeatMin_5`, `delayRepeatMax_5`, `scriptId_5`, `spellId_6`, `probability_6`, `castTarget_6`, `targetParam1_6`, `targetParam2_6`, `castFlags_6`, `delayInitialMin_6`, `delayInitialMax_6`, `delayRepeatMin_6`, `delayRepeatMax_6`, `scriptId_6`, `spellId_7`, `probability_7`, `castTarget_7`, `targetParam1_7`, `targetParam2_7`, `castFlags_7`, `delayInitialMin_7`, `delayInitialMax_7`, `delayRepeatMin_7`, `delayRepeatMax_7`, `scriptId_7`, `spellId_8`, `probability_8`, `castTarget_8`, `targetParam1_8`, `targetParam2_8`, `castFlags_8`, `delayInitialMin_8`, `delayInitialMax_8`, `delayRepeatMin_8`, `delayRepeatMax_8`, `scriptId_8`) VALUES (37500, 'Ashenvale - Foulweald Totemic', 6363, 100, 0, 0, 0, 0, 6, 9, 25, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
> 
> I have fixes for the rest and ALOT more but i don't wanna spam this thread more. @darrowshire-dev ;) you know where to find me

Come on man, dont run away....
