### ISSUE TITLE
Gretheer - NPC - Rare Spawn (Silithus)

### ISSUE THREAD

**Issue by BugTestR** [darrowshire-dev/bugtracker#142]
Greetheer rare spawn level 57 spider in silithus isn't performing deadly poison attacks.
Does cast the spell web but should poison as well. Link to abilities below.
https://classic.wowhead.com/npc=14472/gretheer#abilities

**Comment by rosen40** [comment]
https://i.gyazo.com/e7c776b029bddf2c48357a702953f9cc.png

Wowhead is not a perfect source for accuracy. It is data collected by players in game and tracking what debuffs players had when they fought a mob. In this case you could get Deadly Poisoned by a nearby scorpion and then fight the rare and thats likely how that ability got into that list on Wow head. So no missing abilities here.

**Comment by BugTestR** [comment]
Ok closing it then.
