### ISSUE TITLE
Warlock: Improved Lash of Pain has no effect.

### ISSUE THREAD

**Issue by houdre97** [darrowshire-dev/bugtracker#145]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? https://classic.wowhead.com/spell=18129/improved-lash-of-pain

-- Current behaviour: With 2/2 points in Improved Lash of Pain, Succubus it still has same cooldown of 12 seconds instead of shorter 6 seconds. Addon recognizes that talent points are set in, and starts countdown at 6 seconds, but spell isn't usable until full 12 seconds have passed (using it manually or on autocast)

(Please describe as detailed as possible)

-- Expected behaviour: Should be 6 seconds cooldown time when specced into it.

**Comment by ratkosrb** [comment]
Fixed here https://github.com/vmangos/core/commit/ac0b0494469ebd7923115d51a576515c7398465d

**Comment by darrowshire-dev** [comment]
> Fixed here [vmangos/core@ac0b049](https://github.com/vmangos/core/commit/ac0b0494469ebd7923115d51a576515c7398465d)

Thank you very much for your hard work!
