### ISSUE TITLE
Hillsbrad Footmen ability interactions

### ISSUE THREAD

**Issue by usualtristesse** [darrowshire-dev/bugtracker#146]
-- Current behaviour:

[Hillsbrad footmen](https://classic.wowhead.com/npc=2268/hillsbrad-footman) will use [improved blocking](https://classic.wowhead.com/spell=3419/improved-blocking); however it seems to be linked to their [shield bash ](https://classic.wowhead.com/spell=11972/shield-bash)as I could not get them to use it without channeling a spell and triggering it.

-- Expected behaviour: Improved blocking should activate independently (proc from melee attacks maybe?)

**Comment by rosen40** [comment]
From my testing and obeservation, the Hillsbrad Footmen gain improved blocking as a random proc when hit by a melee attack at 10% chance. Don't see any bugs.

**Comment by usualtristesse** [comment]
Interesting, I thought it was an activated ability rather than a proc. cheers

**Comment by usualtristesse** [comment]
Interesting, I did not think it was a proc but rather an activated ability.
