### ISSUE TITLE
Jailor Eston missing ability

### ISSUE THREAD

**Issue by usualtristesse** [darrowshire-dev/bugtracker#148]
-- Current behaviour:

[Jailor Eston](https://classic.wowhead.com/npc=2427/jailor-eston) currently does not use [Enslave](https://classic.wowhead.com/spell=3442/enslave). While this could be because I engaged him solo, a [comment](https://classic.wowhead.com/npc=2427/jailor-eston#comments:id=45601) from wowhead suggests he should use it regardless

-- Expected behaviour: NPCs using their designated abilities

**Comment by rosen40** [comment]
Yes, he casts Enslave to a random player, except the top threat target, meaning if you are solo, he won't, and while you might consider that as unblizzlike, if he did, you'd both get reset just like that comment, and that wouldn't really achieve anything, would it? We consider THAT a bug, so this is the current intended behavior.

**Comment by usualtristesse** [comment]
Thanks for explaining!
