### ISSUE TITLE
Farmer Kent neutrality

### ISSUE THREAD

**Issue by usualtristesse** [darrowshire-dev/bugtracker#149]
-- Current behaviour: [Farmer Kent](https://classic.wowhead.com/npc=2436/farmer-kent) is currently neutral to Horde players

-- Expected behaviour: Should be hostile according to wowhead

**Comment by NickTyrer** [comment]
he has faction 96 which is correct.

**Comment by usualtristesse** [comment]
I see, thanks. Seems wowheads quick facts box is wrong then.
