### ISSUE TITLE
Silk Cloth dropping from Hillsbrad humanoids

### ISSUE THREAD

**Issue by usualtristesse** [darrowshire-dev/bugtracker#150]
-- Current behaviour: Silk Cloth will sometimes drop from mobs that are below the intended drop level

For example, [Hillsbrad Farmer](https://classic.wowhead.com/npc=2266/hillsbrad-farmer) and [Syndicate Rogue](https://classic.wowhead.com/npc=2260/syndicate-rogue)

<a href="https://ibb.co/B3p9H1s"><img src="https://i.ibb.co/B3p9H1s/Wo-WScrn-Shot-071421-234528.jpg" alt="Wo-WScrn-Shot-071421-234528" border="0"></a>

-- Expected behaviour: Proper loot tables

**Comment by rosen40** [comment]
The links you provided will tell you that they drop Silk Cloth. They correctly drop Silk Cloth.

**Comment by usualtristesse** [comment]
Yeah you're right, thanks for pointing that out
