### ISSUE TITLE
Hillsbrad Councilmen & Frost Nova

### ISSUE THREAD

**Issue by usualtristesse** [darrowshire-dev/bugtracker#151]
-- Current behaviour:

[Hillsbrad Councilman](https://classic.wowhead.com/npc=2387/hillsbrad-councilman) currently uses [Frost Nova ](https://classic.wowhead.com/spell=30094/frost-nova)at a seemingly random interval, not taking into account whether or not he is being attacked from melee range or not

-- Expected behaviour: NPCs using spells in a somewhat intelligent manner

**Comment by rosen40** [comment]
Cannot reproduce. Hillsbrad Councilman properly uses Frost Nova only when you are close enough to get hit by it and he also runs away from you if you are close enough to hit him (as long as he has enough mana).

**Comment by usualtristesse** [comment]
Indeed you're correct, tested this again today and I suspect the reason he stays in melee range is because me (a level 60) resisting all his novas. 

Judging by the details I've overlooked in my recent reports I'm glad that the gelato I smoked was evidently potent
