### ISSUE TITLE
Wailing Caverns - Lord pythas mob linking

### ISSUE THREAD

**Issue by Halahlstrom** [darrowshire-dev/bugtracker#16]
https://classic.wowhead.com/npc=3670/lord-pythas
Lord Pythas currently does not aggro when the group of units around him is pulled.

Seems like Pythas should be aggroed as well when the mobs are pulled

**Comment by darrowshire-dev** [comment]
Noted.

Will be reviewed.

**Comment by MoneyControlStockScraper** [comment]
Just did a run yesterday, and Pythas was aggroed when the druid to his right (left of the player towards the next boss - verdan-the-everliving) was pulled.
