### ISSUE TITLE
Dreadsteed doesn't spawn

### ISSUE THREAD

**Issue by derekvcsr** [darrowshire-dev/bugtracker#167]
https://classic.wowhead.com/spell=23161/summon-dreadsteed
Currently
Dreadsteed for warlocks will make the summoning sound, and give the icon as though I've summoned my Dreadsteed, but it doesn't actually summon it.
Felsteed works fine.
![Dreadsteed-icon-only](https://user-images.githubusercontent.com/40891841/126357473-b2db6464-25ec-4835-a441-4ba10bf6c24c.JPG)

**Comment by darrowshire-dev** [comment]
Since the PTR is on Patch 1.3 the Dreadsteed is not in the game yet ;)
