### ISSUE TITLE
Seal of wrynn bug

### ISSUE THREAD

**Issue by Hushtongs** [darrowshire-dev/bugtracker#178]
Only modifies 2 stats, stamina and spirit. when it's supposed to give some of all stats. The amount of stamina and spirit it modifies is wrong as well. Supposed to only give 3 spirit, it instead gives 6. It gives only 2 stamina, supposed to give 4.

Seal of wrynn wowhead:  https://classic.wowhead.com/item=2933/seal-of-wrynn

Before i put the ring on (pay attention to stats)
![2021-07-21 (2)](https://user-images.githubusercontent.com/87772161/126529556-603ab138-9a59-407a-b434-03f31a43e88a.png)

After i put the ring on
![2021-07-21 (3)](https://user-images.githubusercontent.com/87772161/126529602-c6fee662-b1a5-4721-8e3b-406c47f0d407.png)

**Comment by Stadics** [comment]
Please don't spam the bugtracker with this sort of ill-informed nonsense. The server runs on 1.3, you're talking about the 1.9 stats of the item. Delete your WDB folder, and check classicdb for itemstats before reporting them here.

See https://classicdb.ch/?item=2933-0
