### ISSUE TITLE
Fishing bobber!

### ISSUE THREAD

**Issue by ronaldofenomeno** [darrowshire-dev/bugtracker#18]
Fishing while on a boat makes the bobber land directly under me

![image](https://user-images.githubusercontent.com/33092150/114186570-ae429f80-994f-11eb-88e5-6032aa90b0b4.png)
![image](https://user-images.githubusercontent.com/33092150/114186697-d5996c80-994f-11eb-9aa3-87ad4ec8be54.png)
![image](https://user-images.githubusercontent.com/33092150/114186790-f235a480-994f-11eb-9425-b37db7289725.png)

Also sometimes the fishing wont cast while im on the boat

**Comment by darrowshire-dev** [comment]
Please try again not standing on the Boat.

**Comment by ronaldofenomeno** [comment]
fishing is normal anywhere else but should it also be normal on the boat?!
