### ISSUE TITLE
Mob visibility - The Barrens

### ISSUE THREAD

**Issue by Solomancer** [darrowshire-dev/bugtracker#19]
Perhaps a minor item, but some of the mobs in The Barrens, specifically near the WC tunnel entrance were not visible and seemed to be embedded in the ground texture, making it difficult to see these mobs.

Here's a link to the type of mob it was - Hecklefang Hyena - https://classic.wowhead.com/npc=4127/hecklefang-hyena#drops

![HiddenMobs - Barrens](https://user-images.githubusercontent.com/82280356/114277068-99b9e200-99f7-11eb-891e-301b6eacca6c.jpg)

**Comment by Solomancer** [comment]
![HiddenMobs2 - Barrens](https://user-images.githubusercontent.com/82280356/114277115-dede1400-99f7-11eb-999d-760c03a8fc0e.jpg)

**Comment by darrowshire-dev** [comment]
Clear ur Cache folder. This mostly fixes issues like that!

But we will investigate and take a deeper look into the spawns of these mobs. Maybe something is off.
Thank you for your report!
