### ISSUE TITLE
Copper Veins

### ISSUE THREAD

**Issue by RedPia** [darrowshire-dev/bugtracker#2]
Use the following template:
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)

https://classic.wowhead.com/object=1731/copper-vein

-- Current behaviour:

**Can mine each Copper Vein so far over 10-25x, gives each time loot , no idea if intendet or bug.
Currently only tried in Elwynn Forest.**
(Please describe as detailed as possible)

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)

**Comment by darrowshire-dev** [comment]
Its supposed to be like that on the PTR :)
