### ISSUE TITLE
Map Discovery from Zeppeling

### ISSUE THREAD

**Issue by Solomancer** [darrowshire-dev/bugtracker#20]
While taking the Zeppelin for the first time from Org to UC, my character was able to discover Nightmare Vale (and another location) in Tirisfal Glades through simply moving on the Zeppelin while in transit.  I can't recall if this was how things worked during retail vanilla, but it does seem outside the normal intended map exploration process.

No specific link to wowhead is relevant to this issue.  

Please see screenshot showing the experience gain, while at Zeppelin tower. 
![Nightmare Vale XP](https://user-images.githubusercontent.com/82280356/114277461-48125700-99f9-11eb-9fba-c6e86b45ea91.jpg)

**Comment by ronaldofenomeno** [comment]
i think this is normal
maybe

**Comment by darrowshire-dev** [comment]
Same thing on classic. We think this is intended to be like that!
