### ISSUE TITLE
Quest completion is in English even for non-English clients

### ISSUE THREAD

**Issue by Trust-WoW** [darrowshire-dev/bugtracker#202]
When using a non-English client, the quest progression and completion text that is displayed when you are talking to a quest giver NPC to turn in your quest is displayed in English. Everything else is in the other language, in my case German. When accepting quests, the text is in German. Only affects progression and completion quest texts.

It seems that the server is returning English quest completion texts only, although they should also be available in different languages?

**Comment by ratkosrb** [comment]
The progress and completion texts cannot be bruteforced from official servers, unlike the quest description and objective texts. The only way to receive them from the server is to play with that client and actually do the quest. That is the reason we are missing localization data for quest progress/completion texts in the vmangos database. An alternative way to obtain the translated texts is to parse them from wowhead, but somebody would have to write a parsing tool to do it automatically.

**Comment by Trust-WoW** [comment]
Okay, so basically there is no way to easily "fix" this, right? In that case, please close to issue.

**Comment by ratkosrb** [comment]
Yes make a pull request to update `locales_quest`, but only for `RequestItemsText` and `OfferRewardText`, since we already have the other texts from the bruteforce sniff.

**Comment by Trust-WoW** [comment]
Thank you so much, working flawlessly!
