### ISSUE TITLE
Mining Nodes

### ISSUE THREAD

**Issue by Solomancer** [darrowshire-dev/bugtracker#21]
Nodes in Thunder Ridge - Durotar - are providing excessive ore and stones and not de-psawning after multiple uses. Excessive, meaning 25+ mining occurrences per node.  Perhaps the rates are set a bit high?

https://classic.wowhead.com/object=1731/copper-vein#mining

I will try to grab a screenshot next time it happens and post as a comment.

**Comment by darrowshire-dev** [comment]
Its supposed to be like that on the ptr.
