### ISSUE TITLE
Quest Tracker Duplication

### ISSUE THREAD

**Issue by Solomancer** [darrowshire-dev/bugtracker#22]
Some quest text will double if you have the quest tracker activated prior to collecting any quest completion progress, at which point the text in the tracker will show duplicates. 

No screenshot at the moment, but will follow-up with one next time the issue occurs.

**Comment by ronaldofenomeno** [comment]
has this issue before, too

**Comment by darrowshire-dev** [comment]
A relog will mostly fix this issue.
