### ISSUE TITLE
Anvils in OG are unproportionally big (and maybe other places too)

### ISSUE THREAD

**Issue by jursky** [darrowshire-dev/bugtracker#231]
Hello,
in my honest opinion, Anvils in OG (near the Engineering trainer house) are unproportionally big - visually they don't make any sense. The object (Anvil) should be definitely smaller.

**Comment by NickTyrer** [comment]
The scale of those objects is correct.

**Comment by jursky** [comment]
Did not realize they ought to be THAT big (comparing to Classic). Looks like it is my bad. IMHO that scale does not make sense to me, but that's just me. Closing the issue.
