### ISSUE TITLE
Dustwallow Marsh - Skinning

### ISSUE THREAD

**Issue by Godmatik** [darrowshire-dev/bugtracker#238]
Skinning any mob in Dustwallow Marsh has a chance to result in no leather drop. A beast that can be skinned should always produce a leather.

Never seen this occur in any other zone

**Comment by NickTyrer** [comment]
Which mobs? I just selected one at random and it has the correct skinning loot.

**Comment by Godmatik** [comment]
Every single mob has this property in the zone it appears, as I went to visit it a 2nd time to kill a bunch of the whelps down south, 

Sometimes they drop one leather, sometimes no leather, and sometimes they actually drop two leather which also seems incorrect (one of each kind, like one thick + one heavy)

**Comment by NickTyrer** [comment]
![Untitled](https://user-images.githubusercontent.com/22723839/128624802-f6410fbf-e5b2-4aa3-bc64-1da0b2290a25.png)
The raptors have the correct loot template according to https://classic.wowhead.com/npc=4351/bloodfen-raptor#skinning

**Comment by Godmatik** [comment]
Sorry I don't fully understand this chart, so it is intended that raptors when skinned have a chance to produce no leather when skinned?

**Comment by NickTyrer** [comment]
Correct, do you know if skinning in classic always produced leather?

**Comment by Godmatik** [comment]
As far as I am aware yes but I can't say with fully accuracy, it also seems odd that every other skinnable mob in the game produces a leather 100% of the time but mobs in Dustwallow do not
