### ISSUE TITLE
Quest: "Service to the Horde" is missing

### ISSUE THREAD

**Issue by Godmatik** [darrowshire-dev/bugtracker#239]
After turning in "Report to Zor", the next quest "Service to the Horde" should be available from Zor Lonetree that gives you a ring reward, but he doesn't offer it.

https://classic.wowhead.com/quest=7541/service-to-the-horde
https://classic.wowhead.com/npc=4047/zor-lonetree

**Comment by NickTyrer** [comment]
Dont think that quest is available untill a later patch

**Comment by Godmatik** [comment]
Any info on which patch? 

Looking at wowhead classic there are posts from at least patch 1.4

I recall on Light's Hope this was also an issue in the later patches of the quest not being available

**Comment by NickTyrer** [comment]
Correct, patch 1.4

**Comment by Godmatik** [comment]
Alright, will check back then
