### ISSUE TITLE
Casting & Aggro through objects

### ISSUE THREAD

**Issue by Ash3ndale** [darrowshire-dev/bugtracker#24]
https://youtu.be/z5DJfQSGaOU

As the title says - I am able to cast and aggro mobs through objects such as these huts near razorhill.

**Comment by Ash3ndale** [comment]
https://youtu.be/NHrBrV_MwlI 

Ran some more tests

**Comment by darrowshire-dev** [comment]
Would like to see if these mudhuts break LoS on classic.
