### ISSUE TITLE
[QUEST] The Captain's Chest

### ISSUE THREAD

**Issue by Godmatik** [darrowshire-dev/bugtracker#240]
Quest is not available to be picked up, but should be. 

Comments on Allakhazam go back to patch 1.2

https://classic.wowhead.com/quest=614/the-captains-chest#comments

**Comment by NickTyrer** [comment]
The quest seems correct in vmangos db, are you the correct lvl?

**Comment by Godmatik** [comment]
Yes, it says required minimum level 40, I am 47.

Others in STV reporting same issue.
