### ISSUE TITLE
login

### ISSUE THREAD

**Issue by getthisfixed** [darrowshire-dev/bugtracker#248]
Tried now the last couple of days to get this game to work without luck. Got the client 1.12.1 and set the realmlist to Darrowshire. I then created at account (actually two) but with no respons from here on out. The game starts fine but cant login. Trying since desperately to get in contact with someone that might can help.

**Comment by RossGG** [comment]
I have a similar issue, I am able to log into the server from my desktop/ first device I logged in from. However, I am not able to log in from any other device such as my laptop. Tells me my login information is incorrect even when I copy and paste the exact login info.

**Comment by ZzzaebatsuuU2** [comment]
yea same logon shit with me!

**Comment by ZzzaebatsuuU2** [comment]
lol u just need to enter ur username (not registration e-mail) on login window of game....so idiotic and obvious rofl :DDD
