### ISSUE TITLE
level 11 mob Riverpaw gnoll dropped a level 33 item Keen axe

### ISSUE THREAD

**Issue by xhepxhep** [darrowshire-dev/bugtracker#249]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged?

 https://classic.wowhead.com/npc=117/riverpaw-gnoll

-- Current behaviour:

 Level 11 Riverpaw Gnoll dropped a level 33 item: https://classic.wowhead.com/item=3785/keen-axe

-- Expected behaviour: 

This drop should not be on the loot table of Riverpaw Gnoll

**Comment by scottnice** [comment]
I saw the same thing for the dalaran mages in Silverpine one of them dropped lvl 45 and 25 waters
