### ISSUE TITLE
Ranged Deadzone behaviour mobs

### ISSUE THREAD

**Issue by Ash3ndale** [darrowshire-dev/bugtracker#25]
https://youtu.be/SlBkJh1sZXY

Found some ranged mobs and thought I'd test Deadzoning their shots - they don't seem to switch to melee instantly and you are able to keep them in limbo like that.

**Comment by Ash3ndale** [comment]
https://youtu.be/VDlh7tNv50w

**Comment by ronaldofenomeno** [comment]
what is the name of your bag addon?

**Comment by darrowshire-dev** [comment]
Will be adressed!
