### ISSUE TITLE
error bug all the time

### ISSUE THREAD

**Issue by Vtrex1905** [darrowshire-dev/bugtracker#253]
Hi
i started playing on this server not long ago.. and in like 2-3h of playng i got like 10-15 error bug crshes.. i try all the internet "solutions" and none of them helped me for a long time. when i login into my paladin i got insta crash. can u help me or its my wow copy? 
Ty
![bug2](https://user-images.githubusercontent.com/88800766/129101517-a30bb195-0c5e-40a6-8d9b-229a1dfb943c.png)
![bug](https://user-images.githubusercontent.com/88800766/129101537-5158bbfb-7761-42ba-a68a-9a98fc0fcaa1.png)

**Comment by Godmatik** [comment]
You need to install a new WoW client, the one you have now has corrupt files
