### ISSUE TITLE
Account creation issue

### ISSUE THREAD

**Issue by MarcosTaiss** [darrowshire-dev/bugtracker#258]
I created 2 accounts with 2 different e-mails but i didnt receive any e-mail from darrowshire. I checked the spam and trash boxes and nothing there in both of e-mails(gmail and hotmail). And i tried to register again today but site show me a massage that the e-mail is already registered in site. What i supposed to do? Can someone help me please?

**Comment by ZzzaebatsuuU2** [comment]
Same issue bro
![logon](https://user-images.githubusercontent.com/88886123/129349067-50efd5d3-9baf-4e7b-9b59-ebc7e7114990.png)

**Comment by ZzzaebatsuuU2** [comment]
i dl nostalrius client btw, changed realmlist to ptr.darrowshire.com but still cant login

**Comment by MarcosTaiss** [comment]
> i dl nostalrius client btw, changed realmlist to ptr.darrowshire.com but still cant login

**Comment by MarcosTaiss** [comment]
> Same issue bro
> ![logon](https://user-images.githubusercontent.com/88886123/129349067-50efd5d3-9baf-4e7b-9b59-ebc7e7114990.png)

isnt my problem brother, i dont even received the e-mail from darrowshire to continue create my account.

**Comment by ZzzaebatsuuU2** [comment]
> > Same issue bro
> > ![logon](https://user-images.githubusercontent.com/88886123/129349067-50efd5d3-9baf-4e7b-9b59-ebc7e7114990.png)
> 
> isnt my problem brother, i dont even received the e-mail from darrowshire to continue create my account.

yea me too but i asked others players and they said no verific e-mail doesnt come for them and still they can play

**Comment by ZzzaebatsuuU2** [comment]
I think Darrowshire have some issues with registration of creation new accounts now...

**Comment by MarcosTaiss** [comment]
It worked now. Thx everyone for the help.

**Comment by ZzzaebatsuuU2** [comment]
How u make it worked?

**Comment by ZzzaebatsuuU2** [comment]
> It worked now. Thx everyone for the help.

huh?
