### ISSUE TITLE
Mok'rash - Monogrammed Sash

### ISSUE THREAD

**Issue by Hygnxx** [darrowshire-dev/bugtracker#260]
Mok'rash did not drop the Monogrammed Sash quest item. One party member had already completed the quest and he was tanking and pulled Mok'rash. The sash did not drop for the other two party members that had not yet completed the first quest 

https://classicdb.ch/?quest=8552

**Comment by Hygnxx** [comment]
I tried it again this evening with a fresh party and it still did not drop.

**Comment by ripcurl91** [comment]
drop rate is not 100% - more like something around 70%

**Comment by Hygnxx** [comment]
When your standing on the docks to Booty Bay Mok'rash yells: "I HAVE YOUR LITTLE BELT TIED AROUND MY FINGER, SMOTTS. DON'T YOU WANT IT BACK?" This suggests to me that he has the Monogrammed Sash. I wonder if the drop rate being less than 100% is not due to individuals killing him again, and not being able to loot the belt?
