### ISSUE TITLE
The "following" feature is buged in some cases

### ISSUE THREAD

**Issue by SantiSou** [darrowshire-dev/bugtracker#263]
My friend (Agussou) and I (Wariz) were trying to follow each other and when he is following me and I turn to left/right, he keeps moving forward. 

Regards.

**Comment by Daribon** [comment]
Follow breaks if you run the game above 64 fps.

**Comment by Bignusty** [comment]
I running the game at 60hz and the follow is totally broken

**Comment by SantiSou** [comment]
He's playing on a high resolution than me, maybe that's the problem.
