### ISSUE TITLE
Conjure Water Issue [Low prio]

### ISSUE THREAD

**Issue by SantiSou** [darrowshire-dev/bugtracker#267]
My habiliti is conjuring +4 stacks of water more than the amount it says it would create.

![image](https://user-images.githubusercontent.com/35702273/129486454-0545dc3e-a3ee-4134-8cf5-ad9fde11ac20.png)

**Comment by SantiSou** [comment]
The stack conjured keeps increasing while I level up

**Comment by Godmatik** [comment]
It's supposed to do that
