### ISSUE TITLE
Quest: Troubled Spirits of Kel'Theril

### ISSUE THREAD

**Issue by Hygnxx** [darrowshire-dev/bugtracker#269]
The turn-in NPC Aurora Skycaller is not currently in the game. She should be located in Eastern Plaguelands @ 53 22

I have also checked Quel'Lithien Lodge and did not find her.

**Comment by Daribon** [comment]
Prior to 1.12 she is located in the Northpass tower.

**Comment by Hygnxx** [comment]
I found her today @ 53 22 and was able to complete the quest. She was not in the Northpass tower.
