### ISSUE TITLE
Mountain Lion in Hillsbrad doesn't know prowl.

### ISSUE THREAD

**Issue by Divenity** [darrowshire-dev/bugtracker#271]
The "Mountain Lion", not the "Hulking" or "Starving" ones, just the regular "Mountain Lion" in Hillsbrad is supposed to know Prowl when tamed by a hunter, but does not, see: 

https://www.wow-petopia.com/classic/abilities.php#prowl 
and
https://classic.wowhead.com/npc=2406/mountain-lion#comments:id=2896645 (comment archived from back in 2005 confirming it is supposed to know this ability).

**Comment by Divenity** [comment]
What kind of 'more info' you're looking for? I'm not sure what else I can provide. The mob is supposed to know prowl when tamed by a hunter, but it doesn't - I've provided two sources of evidence that it should know prowl. I don't know what else I'm supposed to tell you here... Could you clarify?

**Comment by Godmatik** [comment]
Patch is on 1.3, those lions dont have prowl yet
