### ISSUE TITLE
NPCs walking on objects

### ISSUE THREAD

**Issue by ronaldofenomeno** [darrowshire-dev/bugtracker#28]
I have posted this previously but i cant find it anymore in the bugtracker. I keep seeing NPCs/Mobs (aggressive and nonaggressive, such as rabbits) walking over objects such as fences, wagons, tables, walls, trees or anything in their path

**Comment by ronaldofenomeno** [comment]
46, 75 elwynn forest: bear and bandit walking on a wagon
31,84 elwynn forest stonetusk boar climbing a tree
riverpaw runt at  31, 88 climbing a tree too

**Comment by ronaldofenomeno** [comment]
![image](https://user-images.githubusercontent.com/33092150/120114750-4d825700-c189-11eb-87e5-16e3f87a3909.png)
![image](https://user-images.githubusercontent.com/33092150/120114761-56732880-c189-11eb-8307-7f2faf4ac721.png) elwynn forest

**Comment by ronaldofenomeno** [comment]
![image](https://user-images.githubusercontent.com/33092150/120114927-18c2cf80-c18a-11eb-9e6d-847b23f387d2.png)

**Comment by ronaldofenomeno** [comment]
bandit and bear walking on wagon. just keep watching for this one
![image](https://user-images.githubusercontent.com/33092150/120114970-5889b700-c18a-11eb-98db-7c1d6ff43ffb.png)

**Comment by ronaldofenomeno** [comment]
![image](https://user-images.githubusercontent.com/33092150/120115560-e9619200-c18c-11eb-890a-83dfc9d6a4a9.png)
elwynn forest

**Comment by ronaldofenomeno** [comment]
defias bandit
![image](https://user-images.githubusercontent.com/33092150/120115619-22016b80-c18d-11eb-8322-95485651ba20.png)

**Comment by ronaldofenomeno** [comment]
![image](https://user-images.githubusercontent.com/33092150/120115810-2c703500-c18e-11eb-9379-7ce31f3b5ada.png)

**Comment by ronaldofenomeno** [comment]
![image](https://user-images.githubusercontent.com/33092150/120115977-8f61cc00-c18e-11eb-81b5-ef2c49cb0041.png)

**Comment by ronaldofenomeno** [comment]
these two walk on top of the pots and the log
![image](https://user-images.githubusercontent.com/33092150/120116048-ee274580-c18e-11eb-899b-29bee39560bf.png)

**Comment by ronaldofenomeno** [comment]
![image](https://user-images.githubusercontent.com/33092150/120116145-5b3adb00-c18f-11eb-932c-4e8de556df6d.png)

**Comment by ronaldofenomeno** [comment]
![image](https://user-images.githubusercontent.com/33092150/120116195-9ccb8600-c18f-11eb-8d26-4c524842ddc8.png)

**Comment by ronaldofenomeno** [comment]
forest's edge
![image](https://user-images.githubusercontent.com/33092150/120116220-cdabbb00-c18f-11eb-8907-e1899bd03415.png)

**Comment by ronaldofenomeno** [comment]
![image](https://user-images.githubusercontent.com/33092150/120116447-df419280-c190-11eb-982e-2a7cab2aae90.png)

**Comment by ronaldofenomeno** [comment]
this kobold miner
![image](https://user-images.githubusercontent.com/33092150/120116590-7870a900-c191-11eb-9ab4-c5018a791f4f.png)

**Comment by ronaldofenomeno** [comment]
murloc forager. watch this one
![image](https://user-images.githubusercontent.com/33092150/120116693-08aeee00-c192-11eb-8a02-f786d346c24b.png)

**Comment by ronaldofenomeno** [comment]
there might be others which i have missed

**Comment by ronaldofenomeno** [comment]
![image](https://user-images.githubusercontent.com/33092150/120117112-4b71c580-c194-11eb-865e-835518691696.png)
cat and cow walk over the water

**Comment by ronaldofenomeno** [comment]
high wilderness cave
![image](https://user-images.githubusercontent.com/33092150/120199876-5bd57f00-c22c-11eb-9cf3-7ff0d66df8b4.png)

**Comment by ronaldofenomeno** [comment]
this one goes through the wall. watch his movement
![image](https://user-images.githubusercontent.com/33092150/120200214-bf5fac80-c22c-11eb-9ea1-048ad9f197b5.png)

**Comment by ronaldofenomeno** [comment]
![image](https://user-images.githubusercontent.com/33092150/121187528-33c3cc80-c879-11eb-8b31-2e0e700c8b6e.png)
walks over fence

**Comment by MoneyControlStockScraper** [comment]
Here is another npc walking on an object


![AnyConv com__WoWScrnShot_061621_192031](https://user-images.githubusercontent.com/84612798/122235205-22af3700-cedb-11eb-9f99-873068954cde.jpeg)

**Comment by darrowshire-dev** [comment]
--fixed
