### ISSUE TITLE
Strath Live epic rain

### ISSUE THREAD

**Issue by vertria** [darrowshire-dev/bugtracker#280]
some of trash live mobs like https://classicdb.ch/?npc=10391 have so high BoE epic drop rates.
how can i prove this?jsut ask people around or check ah.

**Comment by ratkosrb** [comment]
This is blizzlike. The drop rates from the trash mobs were nerfed in patch 1.10.

```
World of Warcraft Client Patch 1.10.0 (2006-03-28)
- The Skeletal Guardian and Skeletal Berserker now drop loot
  appropriate to their non-elite status.
  ```

https://classic.wowhead.com/npc=10390/skeletal-guardian#comments
https://web.archive.org/web/20060831134833/http://wow.allakhazam.com/db/mob.html?wmob=10390

![110016922-48e70780-7d2e-11eb-82ea-de561d6a20d1](https://user-images.githubusercontent.com/35845488/130449482-8a7be130-12b7-40fc-a212-3d13b5978079.jpg)

![110016557-d83feb00-7d2d-11eb-96b6-fe1575be95f8](https://user-images.githubusercontent.com/35845488/130449491-63d573a1-f188-4ab7-bdee-78ccc23de92a.jpg)
