### ISSUE TITLE
cannot log in with the macOS client

### ISSUE THREAD

**Issue by wakanda78** [darrowshire-dev/bugtracker#282]
there is an issue logging in with the macOS client. it says "unable to validate game version...". I'm using 1.12.1 (5875) game client.
![9xb5v6nkx6vz](https://user-images.githubusercontent.com/89280354/130300254-b6d7a1c0-12a4-4372-93b6-83d4295ad099.png)

**Comment by ratkosrb** [comment]
Change the name of WoW Classic.app to World of Warcraft.app

**Comment by wakanda78** [comment]
> Change the name of WoW Classic.app to World of Warcraft.app

have tried it already

**Comment by wakanda78** [comment]
why closed? the issue is not solved
