### ISSUE TITLE
2 mobs stationary and not moving

### ISSUE THREAD

**Issue by ronaldofenomeno** [darrowshire-dev/bugtracker#29]
![image](https://user-images.githubusercontent.com/33092150/115977012-2c23bf00-a57c-11eb-8ff4-ec31ec9a6caa.png)
![image](https://user-images.githubusercontent.com/33092150/115977014-334acd00-a57c-11eb-96c0-9a6faab2bfad.png)
these two mobs at this location are not moving at all.

**Comment by ronaldofenomeno** [comment]
![image](https://user-images.githubusercontent.com/33092150/116005800-3348dc80-a611-11eb-9da3-4ca74a0d49bc.png)
i found more that dont move

**Comment by ronaldofenomeno** [comment]
1 month later, the mobs are still in the same position. 62, 78
![image](https://user-images.githubusercontent.com/33092150/120114669-ebc1ed00-c188-11eb-8d7b-7a35c8416b9e.png)

**Comment by ronaldofenomeno** [comment]
these 4 also which i posted 1 month ago, 59, 75. stationary and dont move
![image](https://user-images.githubusercontent.com/33092150/120114705-18760480-c189-11eb-9ebf-155cdff2a841.png)

**Comment by ronaldofenomeno** [comment]
alot more than this actually. alot of boars in southern elwynn forest dont move/patrol

**Comment by darrowshire-dev** [comment]
--fixed
