### ISSUE TITLE
Kobold Miner in Elwynn Forest named Gizrul the Slavener

### ISSUE THREAD

**Issue by drayp11** [darrowshire-dev/bugtracker#3]
Doing the quest The Jasperlode Mine and the Kobold Miners in front of the mine are all named Gizrul the Slavener (Elite)
![WoWScrnShot_040221_194406](https://user-images.githubusercontent.com/43798598/113461993-e34d7000-93ec-11eb-87a4-421038b9ae68.jpg)

**Comment by darrowshire-dev** [comment]
Please delete your cache/WDB folder. NPC names are probably scuffed due to other servers u have been played on.
I checked the names of the said npcs and they are all correct.
