### ISSUE TITLE
Hillsbrad Tailor not pathing

### ISSUE THREAD

**Issue by LVXVRIA** [darrowshire-dev/bugtracker#31]
There are two hillsbrad tailors inside a house near farmer Kalaba. If you aggro them they get stuck in their house/evade bug. Melee seems to work.

**Comment by LVXVRIA** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/83312195/116309821-3b229100-a777-11eb-94b4-0a7bbd0cb465.png)

**Comment by darrowshire-dev** [comment]
--fixed
