### ISSUE TITLE
Visual bug - Shaman t0 shoulders

### ISSUE THREAD

**Issue by MoneyControlStockScraper** [darrowshire-dev/bugtracker#317]
In the image, you can see the different models on char selection screen and in game.

![2021-09-12 22_11_17-Greenshot](https://user-images.githubusercontent.com/84612798/132995786-c09c4683-2a21-4cdc-bd19-b0f79cc45645.png)

**Comment by Godmatik** [comment]
close game and delete WDB folder

**Comment by MoneyControlStockScraper** [comment]
> close game and delete WDB folder

Thank you, this worked!
