### ISSUE TITLE
Strange Parsing of NPC Event Yells

### ISSUE THREAD

**Issue by redmagejoe** [darrowshire-dev/bugtracker#327]
Most noticeable as an Alliance in Stormwind, but certain NPCs yell as they should, but have their yells preceded by the following "under the hood" text that fills up two extra lines of chat and is very jarring. Currently noticing this on Reginald Windsor and Lady Katrana Prestor during the Stormwind Onyxia event, but also the Defias Messenger in Westfall yelling his secret message to the Defias.

"EVENT: CHAT_MSG_MONSTER_YELL"
"YELL: <NPC Name>"

https://i.imgur.com/X1nCP5x.png

I believe the image speaks for itself.

**Comment by ratkosrb** [comment]
I think you have some kind of addon which prints that.

**Comment by redmagejoe** [comment]
You're right, thought it's, surprisingly, not my chat addon. I'll look into it.
