### ISSUE TITLE
Dustwallow Marsh non-elite enemies doing way too much damage

### ISSUE THREAD

**Issue by Littleslice** [darrowshire-dev/bugtracker#337]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
https://classic.wowhead.com/npc=4324/searing-whelp#drops
https://classic.wowhead.com/npc=4345/drywallow-daggermaw#drops

-- Current behaviour:

They just do way too much damage, the similar, nearby enemies, https://classic.wowhead.com/npc=4323/searing-hatchling and https://classic.wowhead.com/npc=4344/mottled-drywallow-crocolisk do 5 times less damage.

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence) 
Check the combat log in the screenshots underneath.
![Screenshot (107)](https://user-images.githubusercontent.com/43878467/136720348-3683c5bf-a78a-4da8-91eb-b1e052277fb8.png)
![Screenshot (108)](https://user-images.githubusercontent.com/43878467/136720383-e5b2d7b2-cb61-4c51-96ad-17993f07d605.png)

**Comment by Biehrer** [comment]
The same is true for the turtles at the east beach in dustwallow marsh. As a meele its nearly impossible to kill them. Way too much damage
