### ISSUE TITLE
Getting an error when other party member starts a class quest

### ISSUE THREAD

**Issue by ronaldofenomeno** [darrowshire-dev/bugtracker#35]
when a party member started his hunter class quests in Donalaar i keep getting this message. im a druid
![image](https://user-images.githubusercontent.com/33092150/116786120-b51f8680-aaa5-11eb-8a6c-56cb74711b29.png)

**Comment by ronaldofenomeno** [comment]
another quest [Shathra's sacrifice](https://classic.wowhead.com/quest=2520/sathrahs-sacrifice) when accepted by a player it give the option to accept it as if its an escort quest but its not an escort. my party member already done the quest before so he got the message you already completed that quest when i accepted the quest from the NPC.

**Comment by ronaldofenomeno** [comment]
same thing with the druid bear form quest, when i accepted it my party member got the message that he doesnt meet requirments for that quest. quest is [Greater Bear Spirit](https://classic.wowhead.com/quest=5929/great-bear-spirit) in moonglade

**Comment by ronaldofenomeno** [comment]
also [Body and Heart](https://classic.wowhead.com/quest=6002/body-and-heart) druid quest does the same thing for the other party member.

**Comment by darrowshire-dev** [comment]
--fixed
