### ISSUE TITLE
3 Main Bugs in Valley of Trials

### ISSUE THREAD

**Issue by zerkeptr** [darrowshire-dev/bugtracker#36]
1. Charge path is bugged, this happened when I charged the mob on the hill to the right of the cave which is usually standing hidden behind the hill, while I was in front of the hill.
![World Of Warcraft Screenshot 2021 05 04 - 23 44 32 14](https://user-images.githubusercontent.com/83676159/117076172-44db6400-ad36-11eb-8c4f-097b86817662.png)

2. Aggro range is bugged, as you can see in the pic standing steps away and no reaction at all, unless I'm right in front of it. This is the case with pretty much every mob so it's a global bug, happened with Sarkoth as well when he was higher level than me.
![World Of Warcraft Screenshot 2021 05 04 - 23 45 26 65](https://user-images.githubusercontent.com/83676159/117076372-94219480-ad36-11eb-8cfb-ac1fa7c77686.png)

3. This mob I'm attacking is the one that patrols from the orc to the felstalkers, it's pathing stopped at the area I attacked it at and didn't pass the water to the felstalkers as it should.
![World Of Warcraft Screenshot 2021 05 04 - 23 56 41 34](https://user-images.githubusercontent.com/83676159/117076538-d5b23f80-ad36-11eb-8f2e-c9c705604481.png)

**Comment by darrowshire-dev** [comment]
--fixed
