### ISSUE TITLE
Net in Scholomance

### ISSUE THREAD

**Issue by topfreestyle** [darrowshire-dev/bugtracker#37]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
No idea what they are called but the big patroling spiders in scholomance

-- Current behaviour:
If you get netted while sitting down you cannot rise up. And you cannot cast spells while sitting down, so you are stuck in the net sitting and not being able to do anything if you get netted by these guys while sitting down.

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
You should be able to stand up and do everything just like normal.

**Comment by darrowshire-dev** [comment]
Need a comparison with classic on this one.

--closed for now
