### ISSUE TITLE
Atiesh aura

### ISSUE THREAD

**Issue by topfreestyle** [darrowshire-dev/bugtracker#38]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
https://classicdb.ch/?item=22589

-- Current behaviour:
Only tried the mage version but when you die you lose the aura and have to unequip/reequip Atiesh to regain it.

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
You should probably keep it and not have to unequip/reequip it but I don't have proof of this

**Comment by darrowshire-dev** [comment]
Not Gamebreaking.


Low Priority.
