### ISSUE TITLE
(Rogue) Weird delay before Sap

### ISSUE THREAD

**Issue by ripcurl91** [darrowshire-dev/bugtracker#4]
When using Sap as Rogue there is small time window of 0.x seconds where NPCs (and players?) can interact before Sap is cast.

e.g. When you are in Stealth and use Sap, an NPC can hit you before your Sap goes through.

NPCs or players are not supposed to hit you before you cast Sap.

**Comment by darrowshire-dev** [comment]
We will reproduce this and come back to you.

**Comment by darrowshire-dev** [comment]
--fixed
