### ISSUE TITLE
UBRS summoned mobs not disappearing

### ISSUE THREAD

**Issue by topfreestyle** [darrowshire-dev/bugtracker#41]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
https://classicdb.ch/?npc=10680

-- Current behaviour:
They don't despawn in between pulls:
https://i.ibb.co/rKPdFdH/wtf3.png
So we ended up with like 5 extra which we couldn't clear after we wiped, making the instance impossible

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
Should disappear mate

**Comment by darrowshire-dev** [comment]
-fixed
