### ISSUE TITLE
Dire Maul East - Alzzin the wildshaper pathing

### ISSUE THREAD

**Issue by Saiboot** [darrowshire-dev/bugtracker#43]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged?
https://classic.wowhead.com/npc=11492/alzzin-the-wildshaper

-- Current behaviour:
Mob resets upon running into tunnel once it's at 50% health

-- Expected behaviour:
It should follow inside the tunnel to force you to kill it if you want to survive.

- This bug makes it both easier and faster to farm the dungeon for ACs.

**Comment by darrowshire-dev** [comment]
--reset removed

--fixed
