### ISSUE TITLE
Arena spectators in BRD should all be neutral after clearing arena

### ISSUE THREAD

**Issue by topfreestyle** [darrowshire-dev/bugtracker#46]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
https://classicdb.ch/?npc=8893 and more

-- Current behaviour:
After having cleared arena some of the spectators do not get neutral, only the ones called "Arena spectator" do but not everybody on the upper floor (for example, Anvilrage soldiers and Shadowforge peasants stay hostile). Forgot to take a screenshot but yeah this is what happens on the PTR atm

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
As can be seen on this video:
https://www.youtube.com/watch?v=qFWzPAW-M-k
From 24:35 and forward you can see that all of the mobs are yellow after clearing the arena.

**Comment by darrowshire-dev** [comment]
--fixed
