### ISSUE TITLE
Lord Incendius

### ISSUE THREAD

**Issue by topfreestyle** [darrowshire-dev/bugtracker#48]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
https://classicdb.ch/?npc=9017

-- Current behaviour:
Right now you can pull him from up here with no problems and fight him solo:
https://i.ibb.co/mc7gVVy/emberfire.png

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
This should not be the case, if you pull him from upstairs he should pull like 200 guys with him (that's the case on classic, at least).

**Comment by darrowshire-dev** [comment]
-- fixed
