### ISSUE TITLE
Sneaky spot in BRD

### ISSUE THREAD

**Issue by topfreestyle** [darrowshire-dev/bugtracker#49]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
A place in BRD

-- Current behaviour:
On PTR you cannot jump through here:
https://i.ibb.co/Y7X77xr/classic-bug.png

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
I couldn't find any video proof of it happening but I found one video where someone tried to do it:
https://www.youtube.com/watch?v=amyZAs68UkI
At 2 minutes you can see the warrior trying (but not succeeding).
Regardless, this is possible on classic.

**Comment by darrowshire-dev** [comment]
These jumps are never intended to be abused on classic. Same goes for mage-farm aoe safespots. These are bugs in classic itsself and wont be adressed on our server.
