### ISSUE TITLE
Mob aggro range

### ISSUE THREAD

**Issue by Ash3ndale** [darrowshire-dev/bugtracker#5]
Aggressive mobs (in this case Sarkoth https://classic.wowhead.com/npc=3281/sarkoth) doesn't seem to start attacking me until I am almost on top of him.

https://imgur.com/OGgbMEt

It feels off, but then again I do not know exact aggro ranges of aggressive mobs, especially early zone.

**Comment by ripcurl91** [comment]
starting zone mobs have reduced aggro range as far as I know

**Comment by darrowshire-dev** [comment]
Yes the starting area mobs all have reduced aggro range to a certain level.

**Comment by Ash3ndale** [comment]
confirmed, outside valley of trials mobs in green level range do behave according to normal aggro ranges. False alarm I'd say.
