### ISSUE TITLE
Golem Lord Argelmarch

### ISSUE THREAD

**Issue by topfreestyle** [darrowshire-dev/bugtracker#50]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
https://classicdb.ch/?npc=8983

-- Current behaviour:
If you pull him on the PTR without having cleared the previous room then all mobs will aggro:
https://i.ibb.co/wNnC5m9/not-like-classic.png

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
This is not the case on classic, look at this speedrun around 13min:
https://www.youtube.com/watch?v=VuUNtbgNnjQ
At 13:24 for example you can see that there are still mobs to the right that hasn't been pulled even after killing the boss. The only mobs being pulled are the ones the group are pulling themselves. You used to have to clear the entire previous room on pservs but on classic it's not needed.

**Comment by darrowshire-dev** [comment]
Need verification of this. We are not trying to emulate classic.
