### ISSUE TITLE
Ironhand Guardians in BRD (Magmus boss fight)

### ISSUE THREAD

**Issue by topfreestyle** [darrowshire-dev/bugtracker#52]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
Ironhand Guardians in BRD (Magmus boss fight)
https://classicdb.ch/?npc=8982

-- Current behaviour:
Right now the fire guys on the sides are spraying fire before boss fight starts, but do so little damage it's not worth considering:
https://i.ibb.co/kXxjzts/almost-no-damage-lol.png
(The damage isn't low but the frequency is so rare that you can stand in the fire and almost outregen the fire)

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
According to this video from classic:
https://www.youtube.com/watch?v=hnRIUMTjygU
(3h21min in)
You can see that there is no fire spraying until boss is pulled, but that the fire guys on the sides actually do significant damage to the point where you have to avoid the fire. I cannot prove that the damage is different but it felt very weird on the ptr running through the fire and taking so little damage it wasn't even worth considering.

**Comment by darrowshire-dev** [comment]
-- fixed.
