### ISSUE TITLE
Bank Bag Slots

### ISSUE THREAD

**Issue by ZargothCL** [darrowshire-dev/bugtracker#53]
-- What Gameobject:

Bank Bag Slots

-- Current behaviour:

If you attempt to exchange bags by dragging and dropping from your one of your carried slots to an occupied bank bag slot you receive the message "You can only  do that with empty bags"

-- Expected behaviour:

Dragging a bag in either direction should result in an exchange of bags without having to empty them first.

https://classic.wowhead.com/guides/classic-wow-bags-storage#bank-storage

**Comment by darrowshire-dev** [comment]
- fixed
