### ISSUE TITLE
Mage Ice armor removed after duel

### ISSUE THREAD

**Issue by topfreestyle** [darrowshire-dev/bugtracker#54]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
https://classicdb.ch/?spell=10220

-- Current behaviour:
If you lose a duel this spell gets dispelled from you (This is not the case with arcane intellect, for example)

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
You shouldn't lose buffs from losing duels

**Comment by darrowshire-dev** [comment]
--fixed.
