### ISSUE TITLE
Mage Arcane Missiles doesnt trigger procs

### ISSUE THREAD

**Issue by Rat14** [darrowshire-dev/bugtracker#55]
https://classic.wowhead.com/spell=10212/arcane-missiles    (rank 1 - should be able to proc 3 times , rank 2 - 4 times)
All other ranks (3-8) should be able to trigger procs 5 times :
https://classic.wowhead.com/spell=12536/clearcasting (procs only on first missile)
https://classic.wowhead.com/spell=22007/netherwind-focus (procs only on first missile)
https://classic.wowhead.com/spell=28771/elemental-vulnerability (procs only on first missile)
https://classic.wowhead.com/spell=28761/not-there (procs only on first missile)
https://classic.wowhead.com/spell=20355/judgement-of-wisdom (procs only on first missile)
https://classic.wowhead.com/spell=25906/spell-blasting (didnt test this but probably only procs on first missile too)
https://classic.wowhead.com/spell=21978/engulfing-shadows (didnt test this but probably only procs on first missile too)
https://classic.wowhead.com/spell=25767/mystical-disjunction (didnt test this but probably only procs on first missile too)

It should work like this if it was patch 1.0 -1.8 but as its said on https://darrowshire.com/features/ that "Talents and spells will be Blizz-like to patch 1.12.1" its a must fix for arcane mages like myself :)

![1](https://user-images.githubusercontent.com/40735541/119545006-f81a0480-bd9a-11eb-9d81-5a6c947450b4.PNG)
https://vanilla-wow-archive.fandom.com/wiki/Arcane_Missiles
![2](https://user-images.githubusercontent.com/40735541/119545030-fe0fe580-bd9a-11eb-8760-0d31f3bc2668.PNG)
https://wowwiki-archive.fandom.com/wiki/Patch_1.9.0

Also each missile can crit(also be resisted) so it proves that it should also be able to trigger procs from items and spells.

**Comment by darrowshire-dev** [comment]
--fixed
