### ISSUE TITLE
Dead Strat Combat Bug After Baron

### ISSUE THREAD

**Issue by Solomancer** [darrowshire-dev/bugtracker#57]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
Baron Rivendare Event - https://classic.wowhead.com/npc=10440/baron-rivendare

-- Current behaviour:
Following the completion of the fight, character remained in combat with 1 damage ticks continuing to cause damage, as well as daze effect.  Character could move away from this damage, however it would return elsewhere in the cleared instance, following end of Baron fight.  
No damage causing effects were able to clear the player from battle until walking out of the front of the instance. 

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
Character should exit battle following the death of Baron Rivendare. 
Please see this video where the players exit battle at the end of fight upon death of Baron Rivendare.  - https://www.youtube.com/watch?v=RcoHZFQPWwM 

![Strat combat bug1](https://user-images.githubusercontent.com/82280356/119599270-aa10fb00-bdb2-11eb-9dd3-dfa815cc478f.jpg)
![Strat combat bug2](https://user-images.githubusercontent.com/82280356/119599272-aaa99180-bdb2-11eb-8ede-b10a752c0779.jpg)

**Comment by darrowshire-dev** [comment]
It was an invisible entity that is used for spawning the skeletons inside Baron Rivendares room.


--Fixed
