### ISSUE TITLE
Rogue combat points disappear after certain abilities or retargetting

### ISSUE THREAD

**Issue by xdlord1337** [darrowshire-dev/bugtracker#59]
Rogue combat points disappear after mage blink or when retargetting another enemy.

**Comment by mumra** [comment]
Same for druid's cat form. I think this is "normal" behavior until TBC. Change of target causes loss of combo points.

See Patch notes here. https://vanilla-wow-archive.fandom.com/wiki/Combo_point

**Comment by darrowshire-dev** [comment]
Can confirm. The combat points are glued to your current target and are not meant to be switched over to other targets.

--closed

**Comment by xdlord1337** [comment]
I just saw the patch notes you're right it is added in 1.4
