### ISSUE TITLE
Weapon Skills Bug

### ISSUE THREAD

**Issue by Vladimirjov** [darrowshire-dev/bugtracker#6]
Hello
I made a new Character and i noticed that my Weapon Skill got 10/10 and 15/15 after just 1 hit. I think it isn't supposed to level up so quickly and it would take more than 1 hit. Look at the pictures. Is this something u need to fix?

Thank you and see ya ingame

Vladimir

![WoWScrnShot_040421_030427](https://user-images.githubusercontent.com/81888445/113495761-d2d3ed00-94f3-11eb-9f94-8e81c119cb07.png)
![WoWScrnShot_040421_030317](https://user-images.githubusercontent.com/81888445/113495762-d2d3ed00-94f3-11eb-9b10-181673c93673.png)

**Comment by darrowshire-dev** [comment]
This is just a QoL improvement for the time being on PTR. The Skillchance of weapons will be 1x once we launch of course.
No bug. :)
