### ISSUE TITLE
Loot table for The Beast in UBRS

### ISSUE THREAD

**Issue by topfreestyle** [darrowshire-dev/bugtracker#61]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
https://classicdb.ch/?npc=10430
https://classicdb.ch/?item=12967

-- Current behaviour:
https://i.ibb.co/k6CpMdG/double-item.png

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
We got same item x2 but they shouldn't be able to double drop afaik. Not sure though

**Comment by darrowshire-dev** [comment]
droprates on the PTR are multiplied. Won't be the case on live.
