### ISSUE TITLE
Lava spawn in MC

### ISSUE THREAD

**Issue by topfreestyle** [darrowshire-dev/bugtracker#62]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
https://classicdb.ch/?npc=12265

-- Current behaviour:
This guy spawned in the lava and we couldn't kill him (Any attacks were evaded) which led to him multiplying which we couldn't do anything against, leading to an eventual wipe.
https://i.ibb.co/TbXKSsZ/evade.png
It's right in the start, first lava pack, look at the minimap if you are unsure on where it was

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
Well he shouldn't be stuck and invulnerable in the lava

**Comment by darrowshire-dev** [comment]
-- spawnpoint needs to get adjusted.

**Comment by darrowshire-dev** [comment]
--fixed
