### ISSUE TITLE
Barron Charr Yell - Un'Goro

### ISSUE THREAD

**Issue by Solomancer** [darrowshire-dev/bugtracker#65]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
Barron Charr - Fire Elemental in Un'Goro
https://classic.wowhead.com/npc=14461/baron-charr#comments

-- Current behaviour:
Mob yells to announce his presence, however yells are quite frequent, up to 1 per minute, which seems excessive.  This is not a confirmed bug, however it was noticeably prevalent while riding around Un'Goro. 

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
While it's hard to say for certain, in this 1 minute video, Baron Charr does not yell once, implying that the yell time should be less frequent:
https://www.youtube.com/watch?v=f-DUfC2s6TY
![BaronCharr1](https://user-images.githubusercontent.com/82280356/120057053-39feb100-c00e-11eb-9ea5-f0afab5405b9.jpg)

**Comment by darrowshire-dev** [comment]
--fixed
