### ISSUE TITLE
Thunderfury Blade Skin = Black

### ISSUE THREAD

**Issue by Sashwatine** [darrowshire-dev/bugtracker#69]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
Thunderfury, Blessed Blade of the Windseeker

-- Current behaviour:
Enchanted with Crusader, Blade skin appears black on character, not in character screen
![2021-05-29_11h08_41](https://user-images.githubusercontent.com/85014442/120064766-3bf85c80-c06e-11eb-9d6e-1a3350804c90.png)

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
Original Skin on Thunderfury

**Comment by darrowshire-dev** [comment]
This is a client related issue.  The 1.12.1 client tends to bug out graphically. If you use an amd/ATI card, try to use an older graphics card driver --
