### ISSUE TITLE
Professions: Possible Mining Bug

### ISSUE THREAD

**Issue by Vladimirjov** [darrowshire-dev/bugtracker#7]
Hello
When mining i get 13-18 copper ore per node with as many iterations. But according to this classic site... 
https://de.classic.wowhead.com/guides/classic-mining-best-farming-basics-early-ores

... it says as following....

"In Classic: Mines have 2-4 iterations. When you successfully mine it the first time, it doesn't go away, and you will need to continue to mine it out until it disappears. You will only get skill mining out the first iteration."

Is this something u need to fix? I didnt play much vanilla back in the days but i found it surprising that i get so many ores out of 1 node, my inventory fill up quickly :)

Thank you and see you ingame

Vladimir

**Comment by Vladimirjov** [comment]
oh i forgot to mention: since you can hit 1 node 18 times until it disappers,  but you only get 1 Mining skill per node, it makes Mining leveling extremely slow.

**Comment by darrowshire-dev** [comment]
This is just a QoL improvement for the time being on PTR. The Minging of nodes will be 1x once we launch of course.
No bug. :)
