### ISSUE TITLE
No Dismount on Bridge to Blackrock Mountain from Burning Steps

### ISSUE THREAD

**Issue by Sashwatine** [darrowshire-dev/bugtracker#73]
- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
Bridge to Blackrock Mountain from Burning Steps

-- Current behaviour:
No Dismount ( Reindeer)

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
Dismount 
![image](https://user-images.githubusercontent.com/85014442/120243896-079cc000-c269-11eb-97c8-f0c8d8954733.png)

**Comment by darrowshire-dev** [comment]
--fixed

**Comment by ronaldofenomeno** [comment]
> --fixed

i am still mounted on the bridge
![image](https://user-images.githubusercontent.com/33092150/123287283-4dbb0b80-d517-11eb-8094-c01c2350c6dc.png)

**Comment by ronaldofenomeno** [comment]
![image](https://user-images.githubusercontent.com/33092150/123287457-67f4e980-d517-11eb-8b14-ee5dd76d9da2.png)
