### ISSUE TITLE
Visual bug at Ayamiss the Hunter

### ISSUE THREAD

**Issue by Luciuster** [darrowshire-dev/bugtracker#74]
-- Alien-like hive object at Ayamiss the Hunter AQ20 boss

-- Current behaviour:
![WoWScrnShot_053121_225831](https://user-images.githubusercontent.com/85181010/120347432-90b10700-c2fc-11eb-9b14-ac2a2f6d290b.png)

At certain camera angles gets an erection

-- Expected behaviour: Not horny

![WoWScrnShot_053121_225829](https://user-images.githubusercontent.com/85181010/120347781-de2d7400-c2fc-11eb-9f4b-d3d216a61e72.png)

**Comment by darrowshire-dev** [comment]
this is a known issue on the 1.12.1 client. Try to use an older graphics card driver if you are on amd/ATI --
