### ISSUE TITLE
Drain mana animation in AQ20 on Moam

### ISSUE THREAD

**Issue by topfreestyle** [darrowshire-dev/bugtracker#75]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
Drain mana (https://classicdb.ch/?spell=11704) on Moam (https://classicdb.ch/?npc=15340)

-- Current behaviour:
https://i.ibb.co/yXTfHVQ/Namnl-s.png
Drain mana doesn't have an animation on this particular boss, there's no "strain" between me and the boss

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
It should look like normal

**Comment by darrowshire-dev** [comment]
This might be an client sided issue.

Try to use an older driver for your graphics card if you are on amd/ATI.
We tryed to reproduce it but the animation is working as intended.
