### ISSUE TITLE
Overmaster Pyron not dropping aggro after going into BRD

### ISSUE THREAD

**Issue by Siptime** [darrowshire-dev/bugtracker#76]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
Overmaster Pyron https://classic.wowhead.com/npc=9026/overmaster-pyron

-- Current behaviour:
Will wait outside of brd after you have gone into the instance. Will attack you again when you leave the instance as if you still have aggro.

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
Drop aggro and return to normal patrol route once you enter the instance.

**Comment by Siptime** [comment]
After further testing this seems to happen with any NPC in the game. And is not exclusive to Overmaster Pyron.

**Comment by ronaldofenomeno** [comment]
> After further testing this seems to happen with any NPC in the game. And is not exclusive to Overmaster Pyron.

looks like many bugs affect many NPCs in the game. like the pathing bug, affecting many mobs in elwynn, especially boars making them walk on top of objects.

**Comment by ronaldofenomeno** [comment]
can confirm this aggro issue with the mobs outside of deadmines 
![image](https://user-images.githubusercontent.com/33092150/121189268-feb87980-c87a-11eb-9828-3903e1a35fcf.png)

**Comment by darrowshire-dev** [comment]
the mobs will now reset after a period of time.

--fixed
