### ISSUE TITLE
Not getting dismounted in water

### ISSUE THREAD

**Issue by Pirupuku** [darrowshire-dev/bugtracker#86]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged? (Please use https://classic.wowhead.com)
I am not getting dismounted in water where I should get dismounted

-- Current behaviour:
Not getting dismounted in water, moving slow as I am swimming but I am still on the mount.

-- Expected behaviour: (Use screenshots, gifs, videos or https://classic.wowhead.com for evidence)
The water in the image is not that deep but without mount I would swim there. That means I should get dismounted. My guess is that mounted I would not swim there (comparable to Tauren/Gnome -> Tauren some times walk through water where Gnomes already swim) so that's why I am not getting dismounted. But not entirely sure why is that...
![not dismounting](https://user-images.githubusercontent.com/55432521/121809079-b541a300-cc5b-11eb-9b66-eea7e577d2d6.PNG)

**Comment by darrowshire-dev** [comment]
-- fixed
