### ISSUE TITLE
NPC not aggressive (Update 10 different NPCs are not aggressive)

### ISSUE THREAD

**Issue by MoneyControlStockScraper** [darrowshire-dev/bugtracker#87]
https://classicdb.ch/?npc=3846

Standing on top of the NPC does not aggro him.

![WoWScrnShot_061521_111109-min](https://user-images.githubusercontent.com/84612798/122000553-a4fd0580-cdcc-11eb-9e70-0d422d937bf6.jpg)

**Comment by darrowshire-dev** [comment]
We have to make sure, that this Mob is agressive on Classic.

**Comment by MoneyControlStockScraper** [comment]
Same bug on 2 more NPCs. 1 is a Skull level NPC as well
![WoWScrnShot_061521_114522-min](https://user-images.githubusercontent.com/84612798/122002587-9106d300-cdcf-11eb-91f6-e07633ebe5d0.jpg)
![WoWScrnShot_061521_114545-min](https://user-images.githubusercontent.com/84612798/122002593-93692d00-cdcf-11eb-9c4f-7103ba6c19b0.jpg)

**Comment by MoneyControlStockScraper** [comment]
This is a bug 100%
![WoWScrnShot_061521_114912-min](https://user-images.githubusercontent.com/84612798/122002842-e4792100-cdcf-11eb-8588-e33ba6c1a772.jpg)

**Comment by MoneyControlStockScraper** [comment]
2 more NPC https://classicdb.ch/?npc=3847 and https://classicdb.ch/?npc=4484 are also not aggressive.
![WoWScrnShot_061521_121354-min](https://user-images.githubusercontent.com/84612798/122006093-0d031a00-cdd4-11eb-8951-d4fb6a71e82e.jpg)
![WoWScrnShot_061521_121359-min](https://user-images.githubusercontent.com/84612798/122006097-0f657400-cdd4-11eb-81bb-c839bce76e97.jpg)

This is not the case for all alliance NPC in ashenvale. Another NPC https://classic.wowhead.com/npc=11712/lilyn-darkriver
This NPC is aggressive.
![WoWScrnShot_061521_121550-min](https://user-images.githubusercontent.com/84612798/122006309-4c316b00-cdd4-11eb-9429-f68393f841a6.jpg)

**Comment by MoneyControlStockScraper** [comment]
https://classic.wowhead.com/npc=3951/bhaldaran-ravenshade
![WoWScrnShot_061521_122626-min](https://user-images.githubusercontent.com/84612798/122007744-e47c1f80-cdd5-11eb-9964-3000b609388b.jpg)

https://classicdb.ch/?npc=3955
![AnyConv com__WoWScrnShot_061521_122733-min](https://user-images.githubusercontent.com/84612798/122007754-e645e300-cdd5-11eb-98ba-1d50fe793be3.jpg)

https://classic.wowhead.com/npc=4320/caelyb
![AnyConv com__WoWScrnShot_061521_122905-min](https://user-images.githubusercontent.com/84612798/122007755-e6de7980-cdd5-11eb-979b-e8b10e112e5f.jpg)

https://www.classicdb.ch/?npc=3885
![AnyConv com__WoWScrnShot_061521_122909-min](https://user-images.githubusercontent.com/84612798/122007757-e7771000-cdd5-11eb-9f74-a6fec1bfa5af.jpg)

**Comment by MoneyControlStockScraper** [comment]
So i checked the same thing out on elysium and those npcs are not aggressive on that server!
