### ISSUE TITLE
High level spells on low level toon

### ISSUE THREAD

**Issue by MoneyControlStockScraper** [darrowshire-dev/bugtracker#88]
After changing spec, level and gear from the winterspring NPC, the high level spells remain in spellbook and can be cast.
![WoWScrnShot_061521_112848-min](https://user-images.githubusercontent.com/84612798/122001392-e93cd580-cdcd-11eb-8362-a4cff93597fe.jpg)

**Comment by darrowshire-dev** [comment]
This will not be possible on live.

The NPC mechanic of learning these spells instantly will not be present.
