### ISSUE TITLE
Aggro range - Mob not Agrroing inspite of mob next to it being in combat

### ISSUE THREAD

**Issue by MoneyControlStockScraper** [darrowshire-dev/bugtracker#92]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged?
https://classic.wowhead.com/npc=7115/jaedenar-adept

--Current Behaviour:
This SS clearly shows problems with mob linking and aggro

![AnyConv com__WoWScrnShot_061521_134457-min](https://user-images.githubusercontent.com/84612798/122018134-32962080-cde0-11eb-9295-db0c76492baa.jpeg)

--Expected Behaviour:
Mob should aggro when you are killing the mob next to it.

**Comment by MoneyControlStockScraper** [comment]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged?
https://classic.wowhead.com/npc=7125/jaedenar-hound

--Current Behaviour:
Im so close to it and attacking a mob near it and yet it does not aggro.
![2](https://user-images.githubusercontent.com/84612798/122662984-cc7d1500-d1b4-11eb-90b9-240680a8fd56.jpeg)
![1](https://user-images.githubusercontent.com/84612798/122662988-d141c900-d1b4-11eb-987d-960ad477de7b.jpeg)

--Expected Behaviour: Beast should aggro when killing the mob next to it.

**Comment by MoneyControlStockScraper** [comment]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged?
https://classic.wowhead.com/npc=672/skullsplitter-spiritchaser

--Current Behaviour:
Does not heal mobs from other packs which are not linked.

https://user-images.githubusercontent.com/84612798/122674501-269ccb00-d1f3-11eb-9141-dcbc0b2bedcd.mp4

--Expected Behaviour: Similar to the previous reports, mob should aggro and heal other mobs which are nearby regardless if they are the part of the same spawn/pack.

PS: Implementing this change and the healing npc scripts will increase the difficulty and provide a FRESH experience on a 17 year old game and a new take on leveling experience.

**Comment by ratkosrb** [comment]
Mobs do not do their periodic call for help if they are less than 10 yards from their spawn position. This is to prevent the chain pulling bug where you pull 1 mob, it pulls a nearby one, that nearby one pulls a different mob that is near to it but far away from the original one, and so on until all mobs in the area are now in aggro with you, even if most of them were quite far from the original mob you pulled.

**Comment by MoneyControlStockScraper** [comment]
> Mobs do not do their periodic call for help if they are less than 10 yards from their spawn position. This is to prevent the chain pulling bug where you pull 1 mob, it pulls a nearby one, that nearby one pulls a different mob that is near to it but far away from the original one, and so on until all mobs in the area are now in aggro with you, even if most of them were quite far from the original mob you pulled.

If you take a look at the screenshot of the jaedenar hounds, they are standing at their spawn point and they do not aggro when you aggro the mob standing right next to them. On the other hand, some other hounds DO aggro when you aggro the mob next to them. Must be some linking issue for specific NPCs.
