### ISSUE TITLE
PvP NPCs dont aggro alliance players in kargath

### ISSUE THREAD

**Issue by ronaldofenomeno** [darrowshire-dev/bugtracker#96]
![image](https://user-images.githubusercontent.com/33092150/122064511-43f02480-ce02-11eb-9c79-e430ae1ded51.png)

not very sure about this. the guards aggro us. but shouldnt other pvp non-vendor NPCs attack us, too?

**Comment by darrowshire-dev** [comment]
No they are not supposed to attack you before you attack first.
