### ISSUE TITLE
Can understand undead npc speech as alliance

### ISSUE THREAD

**Issue by MoneyControlStockScraper** [darrowshire-dev/bugtracker#97]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged?
https://classic.wowhead.com/npc=9079/hierophant-theodora-mulvadania
https://classic.wowhead.com/npc=9078/shadowmage-vivian-lagrave

--Current Behaviour: As seen in ss, alliance player can read what their dialog is.

![AnyConv com__WoWScrnShot_061521_191929](https://user-images.githubusercontent.com/84612798/122064791-09d94f80-ce0f-11eb-98ba-6e0676949c7a.jpg)

--Expected Behaviour: Simillar to the orc dialog in the ss, the 2 undead NPC dialog should be unreadable for alliance characters.

**Comment by darrowshire-dev** [comment]
It wont be possible on live. This happens because we enabled crossfaction on the PTR and this enables to understand every language.
