### ISSUE TITLE
Wailing caverns raptors not calling for help when low 

### ISSUE THREAD

**Issue by MoneyControlStockScraper** [darrowshire-dev/bugtracker#99]
-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged?
https://classic.wowhead.com/npc=3637/deviate-guardian#abilities;mode:normal

--Current Behaviour: Does not call for help when low hp
--Expected Behaviour: Should call for help when low hp - shriek as a emote in orange to call for help and aggro nearby raptors but its not happening
 
![AnyConv com__WoWScrnShot_061521_195021](https://user-images.githubusercontent.com/84612798/122070007-3f803780-ce13-11eb-8b59-eb6942056829.jpg)

**Comment by ronaldofenomeno** [comment]
in the chat the raptors should shriek as a emote in orange to call for help and aggro nearby raptors but its not happening

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/26b88d59b9be0527931f1ec3ada366f673898327
